//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchingLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreasOfCity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreasOfCity()
        {
            this.Announcing = new HashSet<Announcing>();
        }
    
        public int Areas_id { get; set; }
        public string Areas_name { get; set; }
        public int City_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Announcing> Announcing { get; set; }
        public virtual Cities Cities { get; set; }
    }
}
