//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchingLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SearchingEntities : DbContext
    {
        public SearchingEntities()
            : base("name=SearchingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcing> Announcing { get; set; }
        public virtual DbSet<AreasOfCity> AreasOfCity { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Favorite_Announcing> Favorite_Announcing { get; set; }
        public virtual DbSet<Selected_Announcing> Selected_Announcing { get; set; }
        public virtual DbSet<Selected_User> Selected_User { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserList> UserList { get; set; }
    }
}
