//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchingLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class UserList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserList()
        {
            this.Announcing = new HashSet<Announcing>();
            this.Favorite_Announcing = new HashSet<Favorite_Announcing>();
            this.Selected_Announcing = new HashSet<Selected_Announcing>();
            this.Selected_User = new HashSet<Selected_User>();
            this.Selected_User1 = new HashSet<Selected_User>();
        }
        [DataMember]
        public int User_id { get; set; }
        [DataMember]
        public string Mail { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string LastName { get; set; }
        [DataMember]
        public string Phone { get; set; }
        [DataMember]
        public string Gender_user { get; set; }
        [DataMember]
        public DateTime? Date_Bearthday { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public string Info { get; set; }
        [DataMember]
        public int? Country_id { get; set; }
        [DataMember]
        public byte? Type_login { get; set; }
        [DataMember]
        public int? City_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Announcing> Announcing { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite_Announcing> Favorite_Announcing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selected_Announcing> Selected_Announcing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selected_User> Selected_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selected_User> Selected_User1 { get; set; }
    }
}
